#!/usr/bin/env python3
"""Multi-agent reviewer for GitHub pull requests and issues. See ARCHITECTURE.md."""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path

import git_io
import github_io
import repo_facts
import session_builder

ROOT = Path(__file__).resolve().parent
DEFAULT_WORKDIR = Path("./repo")
DEFAULT_API_BASE = "https://api.openai.com/v1"
# The checkout is reachable through read_file, and the topic is replayed into
# every turn of a ~60-call session, so the inline diff is kept modest.
DIFF_BUDGET_BYTES = 60 * 1024
PROMPTS_DIR = ROOT / "prompts"
# Per-repo knowledge lives under repos/<owner>/<name>/; anything the profile
# does not carry falls back to default/, then to the shared prompts root.
REPO_PROFILES_DIR = PROMPTS_DIR / "repos"
DEFAULT_PROFILE_DIR = PROMPTS_DIR / "default"
# GitHub's own owner/repo charset. This value reaches both a filesystem path
# (the profile lookup, the clone directory) and a subprocess argv, so it is
# validated rather than trusted.
REPO_PART_RE = re.compile(r"^[A-Za-z0-9._-]+$")
FOOTER_TEMPLATE = "\n\n---\n*🤖 generated by `review.py` ({model})*"
# Last phase of both gameplans. A panel that stopped earlier skipped checks.
FINAL_PHASE = "verify"
# The severities the rubric's approve threshold turns on: either one present
# means the change may not merge, so the summary gives each its own section.
BLOCKING = ("blocker", "major")
# Lines quoted either side of a finding's own line, and the per-line clip. Wide
# enough to show the statement in its context, narrow enough that a review with
# several findings stays readable in a GitHub notification.
EXCERPT_CONTEXT_LINES = 3
EXCERPT_MAX_LINE_CHARS = 200
# A proposed fix is a sketch, not a patch. Past this it is doing the author's
# work for them, in a comment nobody will read to the end.
FIX_CODE_MAX_LINES = 20
# Fence language for the proposed fix, so it highlights as the language it is
# in. Scoped to the same set repo_facts.INDENT_LANGS measures; anything else
# gets a plain fence rather than a guess.
FENCE_LANGS = {
    ".py": "python", ".c": "c", ".h": "c", ".cpp": "cpp", ".hpp": "cpp",
    ".rs": "rust",
    ".sh": "sh", ".yml": "yaml", ".yaml": "yaml", ".toml": "toml",
}

CHECK_TITLES = {
    "style": "1. Coding style per language",
    "naming": "2. Naming conventions",
    "duplication": "3. Duplicate / near-duplicate code",
    "quality": "4. Code quality",
    "fit": "5. Fit with the project",
    "dependencies": "6. Dependencies and supply chain",
    "security": "7. Security",
}


def normalize_repo(value: str) -> str:
    """Accept the URL forms people paste, return canonical `owner/name`.

    `owner/name`, `github.com/owner/name`, `https://github.com/owner/name`,
    and `git@github.com:owner/name.git` all name the same repository. Only
    github.com is accepted: every GitHub call in this tool goes through `gh`
    against github.com (guardrail 1), so another host would silently review
    the wrong thing.
    """
    text = value.strip().removesuffix("/")
    text = re.sub(r"^(?:https?://|git\+https?://|ssh://)", "", text)
    text = re.sub(r"^git@([^:]+):", r"\1/", text)
    text = re.sub(r"^[^/]*@", "", text)  # https://user@github.com/o/n
    if "/" in text:
        host, _, rest = text.partition("/")
        if "." in host:
            if host.lower() not in ("github.com", "www.github.com"):
                raise SystemExit(
                    f"error: --repo {value!r} names host {host!r}; only github.com "
                    f"is supported (all GitHub access goes through `gh`)."
                )
            text = rest
    text = text.removesuffix(".git")

    parts = text.split("/")
    if len(parts) != 2 or not all(REPO_PART_RE.match(p) and p not in (".", "..") for p in parts):
        raise SystemExit(
            f"error: --repo {value!r} is not a GitHub repository. Expected "
            f"OWNER/NAME or https://github.com/OWNER/NAME."
        )
    return "/".join(parts)


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser(
        description="Multi-agent LLM reviewer for GitHub pull requests and issues.",
    )
    ap.add_argument("kind", choices=["pr", "issue"])
    ap.add_argument("number", type=int)
    ap.add_argument(
        "--api-key", default=os.environ.get("REVIEW_API_KEY"),
        help="API key for the OpenAI-compatible endpoint (or $REVIEW_API_KEY). "
             "Never written to disk.",
    )
    ap.add_argument(
        "--api-base", default=os.environ.get("REVIEW_API_BASE", DEFAULT_API_BASE),
        help=f"Base URL of the endpoint (or $REVIEW_API_BASE, default {DEFAULT_API_BASE})",
    )
    ap.add_argument(
        "--llm-model", default=os.environ.get("REVIEW_MODEL"),
        help="Model name to drive every agent with (or $REVIEW_MODEL)",
    )
    ap.add_argument(
        "--repo", required=True,
        help="repository to review: OWNER/NAME or a github.com URL",
    )
    ap.add_argument(
        "--prompts", type=Path, default=None,
        help="directory of knowledge files for this repo (ARCHITECTURE.md, "
             "design.md, coding_styles.md); overrides the prompts/repos/ lookup",
    )
    ap.add_argument(
        "--base-branch", default=None,
        help="branch to reset the checkout to (default: the PR's own base, "
             "then the profile's pin, then the repo's GitHub default branch)",
    )
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument(
        "--allow-approve", action="store_true",
        help="allow posting a real GitHub approval when the panel proposes one "
             "(default: approvals are downgraded to comments)",
    )
    ap.add_argument("--workdir", type=Path, default=DEFAULT_WORKDIR)
    ap.add_argument(
        "--timeout", type=int, default=180,
        help="per-request HTTP timeout in seconds (default: 180)",
    )
    ap.add_argument(
        "--max-turns", type=int, default=None,
        help="override the gameplan's turn ceiling (default: the gameplan's own)",
    )
    ap.add_argument(
        "--transcript", type=Path, default=None,
        help="also write the panel transcript to this file",
    )
    args = ap.parse_args()
    if not args.api_key:
        ap.error("--api-key is required (or set $REVIEW_API_KEY)")
    if not args.llm_model:
        ap.error("--llm-model is required (or set $REVIEW_MODEL)")
    args.repo = normalize_repo(args.repo)
    return args


def resolve_profile(repo: str, override: Path | None) -> Path:
    """The knowledge directory this run reads from.

    An explicit `--prompts` wins; otherwise a repo with a profile under
    `prompts/repos/` gets it, and everything else gets the generic fallback.
    """
    if override is not None:
        if not override.is_dir():
            raise SystemExit(f"error: --prompts {override} is not a directory.")
        return override
    owner, name = repo.split("/")
    profile = REPO_PROFILES_DIR / owner / name
    return profile if profile.is_dir() else DEFAULT_PROFILE_DIR


def profile_base_branch(profile: Path) -> str | None:
    """The branch this profile pins, if it pins one.

    Exists for projects whose working branch is not their GitHub default, which
    `gh` is the only other source for: a project that develops on `dev` while
    its `master` sits stale would otherwise be reviewed against the stale one.
    """
    path = profile / "profile.json"
    if not path.exists():
        return None
    try:
        data = json.loads(path.read_text())
    except json.JSONDecodeError as exc:
        raise SystemExit(f"error: {path} is not valid JSON: {exc}")
    if not isinstance(data, dict):
        raise SystemExit(f"error: {path} must contain a JSON object.")
    branch = data.get("base_branch")
    return str(branch) if branch else None


def resolve_base_branch(repo: str, profile: Path, override: str | None, pr_base: str | None) -> str:
    """Which branch to reset the clone to, most specific source first.

    The GitHub lookup is last and lazy: a repo whose branch is already known
    from the PR or from its profile costs no extra call.
    """
    for branch in (override, pr_base, profile_base_branch(profile)):
        if branch:
            return branch
    return github_io.fetch_default_branch(repo)


def _read_prompt(profile: Path, name: str, *, required: bool) -> str:
    """First hit along profile → default profile → shared prompts root.

    So a profile carries only what it wants to say: `coding_styles.md` stays
    shared unless a project overrides it, and `default/` backstops the rest.
    """
    for directory in (profile, DEFAULT_PROFILE_DIR, PROMPTS_DIR):
        path = directory / name
        if path.exists():
            return path.read_text()
    if required:
        raise SystemExit(
            f"error: required prompt file {name} was not found in {profile}, "
            f"{DEFAULT_PROFILE_DIR}, or {PROMPTS_DIR}."
        )
    return f"({name} not provided)"


def _truncate(text: str, budget: int = DIFF_BUDGET_BYTES) -> str:
    raw = text.encode("utf-8")
    if len(raw) <= budget:
        return text
    head = raw[:budget].decode("utf-8", errors="ignore")
    return head + (
        f"\n\n[... diff truncated at {budget} bytes. The full checkout is "
        f"available through read_file — go read the rest ...]"
    )


def _files_summary(pr: dict) -> str:
    files = pr.get("files") or []
    if not files:
        return "(none)"
    return "\n".join(
        f"- {f.get('path', '?')} (+{f.get('additions', 0)}/-{f.get('deletions', 0)})"
        for f in files
    )


def _comments_block(issue: dict) -> str:
    comments = issue.get("comments") or []
    if not comments:
        return "(no comments)"
    return "\n\n".join(
        f"**@{(c.get('author') or {}).get('login', '?')}**: {c.get('body', '')}"
        for c in comments
    )


def _labels_summary(issue: dict) -> str:
    labels = issue.get("labels") or []
    return ", ".join(l.get("name", "") for l in labels) or "(none)"


def build_pr_topic(pr: dict, diff: str, facts: str, clone: Path, profile: Path) -> str:
    return f"""Review pull request #{pr.get('number')} of {pr.get('url', '')}.

A read-only checkout of this pull request is at `{clone.resolve()}`. Pass paths
under it to read_file and list_dir. Nothing outside it is readable, and no
command can be run — you cannot build or execute this submission, by design.

# Project architecture (factual reference)

{_read_prompt(profile, 'ARCHITECTURE.md', required=False)}

# Review rubric — severity, and the approve threshold

{_read_prompt(profile, 'design.md', required=True)}

# Per-language style reference

{_read_prompt(profile, 'coding_styles.md', required=True)}

# Measured facts about this pull request

{facts}

# The pull request

**Title:** {pr.get('title', '')}
**Author:** @{(pr.get('author') or {}).get('login', '?')}
**State:** {pr.get('state', '?')} (draft={str(bool(pr.get('isDraft'))).lower()})
**Base → Head:** {pr.get('baseRefName', '?')} → {pr.get('headRefName', '?')}

**Description:**
{pr.get('body') or '(no description)'}

**Touched files:**
{_files_summary(pr)}

**Unified diff:**
```diff
{_truncate(diff)}
```
"""


def build_issue_topic(issue: dict, clone: Path, profile: Path) -> str:
    return f"""Triage issue #{issue.get('number')} of {issue.get('url', '')}.

A read-only checkout of the project is at `{clone.resolve()}`. Pass paths under
it to read_file and list_dir. Nothing outside it is readable and no command can
be run.

# Project architecture (factual reference)

{_read_prompt(profile, 'ARCHITECTURE.md', required=False)}

# The issue

**Title:** {issue.get('title', '')}
**Author:** @{(issue.get('author') or {}).get('login', '?')}
**State:** {issue.get('state', '?')}
**Labels:** {_labels_summary(issue)}

**Body:**
{_truncate(issue.get('body') or '(no description)')}

**Comments:**
{_truncate(_comments_block(issue))}
"""


def require_body(fields: dict, result, key: str) -> str:
    """The panel's posted text, or a hard stop.

    kerness never fails result parsing — a model that botches the closing JSON
    block yields type-appropriate defaults, which for a string field is "".
    An empty review must not reach GitHub, so this is where that ends.
    """
    body = (fields.get(key) or "").strip()
    if body:
        return body
    summary = (result.summary or "").strip()
    if summary:
        print(
            f"warning: panel returned no `{key}`; falling back to the session summary.",
            file=sys.stderr,
        )
        return summary
    raise SystemExit(
        f"error: panel produced neither `{key}` nor a summary "
        f"(ended: {result.end_reason!r} at phase {result.phase_reached!r}). "
        f"Nothing posted."
    )


def require_completed_panel(result) -> None:
    """Refuse to post a review whose panel never reached the verify phase.

    `terminate_on` fires wherever the keyword appears, so an orchestrator that
    writes it during phase one ends the session there — and still produces a
    confident-looking verdict for the six checks that never ran. That review
    reads exactly like a real one. The phase the panel actually reached is the
    only reliable evidence it did the work, so it is checked here rather than
    trusted to the prompt.
    """
    if result.phase_reached == FINAL_PHASE:
        return
    raise SystemExit(
        f"error: the panel ended at phase {result.phase_reached!r} "
        f"(reason: {result.end_reason!r}, {result.turns_completed} turns) "
        f"without reaching {FINAL_PHASE!r}. Its checks are incomplete, so its "
        f"verdict is not trustworthy. Nothing posted — re-run, and raise "
        f"--max-turns if the panel ran out of budget."
    )


def downgrade_if_needed(fields: dict) -> tuple[dict, str | None]:
    findings = [f for f in (fields.get("findings") or []) if isinstance(f, dict)]
    fields["findings"] = findings
    has_blocker = any(f.get("severity") in BLOCKING for f in findings)
    if fields.get("verdict") == "approve" and has_blocker:
        fields["verdict"] = "comment"
        return fields, (
            "_Note: the panel proposed `approve` but raised major/blocker findings. "
            "Downgraded to `comment` for maintainer review._"
        )
    return fields, None


def _location(f: dict) -> str:
    loc = f.get("file") or ""
    line = f.get("line")
    if loc and line:
        return f"`{loc}:{line}`"
    if loc:
        return f"`{loc}`"
    return "_(no location given)_"


def _one_line(text) -> str:
    """Collapse a message to one line so it cannot break out of its list item."""
    return " ".join(str(text or "").split())


def quote_code(clone: Path, f: dict) -> str:
    """Quote the cited code out of the PR's own checkout.

    The excerpt is read here rather than taken from the panel, so what the
    contributor reads is the code they wrote, at the line the finding names,
    and not a model's recollection of it. A finding whose path or line is not
    in the checkout cannot be quoted, and says so where the code would have
    been: unverifiable is a visible state, not a silently missing block.
    """
    name = str(f.get("file") or "").strip()
    if not name:
        return "_This finding cites no file, so no code could be quoted._"
    root = clone.resolve()
    target = (root / name).resolve()
    # The path comes out of the model, so it is confined the same way the
    # panel's own reads are: nothing outside the checkout is opened.
    if not target.is_relative_to(root) or not target.is_file():
        return f"_`{name}` is not in the checkout, so this finding is unverified._"
    try:
        source = target.read_text(errors="replace").splitlines()
    except OSError:
        return f"_`{name}` could not be read from the checkout._"
    try:
        cited = int(f.get("line"))
    except (TypeError, ValueError):
        return f"_This finding cites no line in `{name}`, so no code could be quoted._"
    if not 1 <= cited <= len(source):
        return f"_`{name}` has no line {cited}, so this finding is unverified._"

    first = max(1, cited - EXCERPT_CONTEXT_LINES)
    last = min(len(source), cited + EXCERPT_CONTEXT_LINES)
    width = len(str(last))
    # No language on the fence: the line numbers and the `>` marking the cited
    # line are what the finding points at, and syntax highlighting would colour
    # them as if they were code.
    body = "\n".join(
        f"{'>' if n == cited else ' '} {n:>{width}} | {source[n - 1][:EXCERPT_MAX_LINE_CHARS]}"
        for n in range(first, last + 1)
    )
    return _fence(body, "")


def _fence(body: str, lang: str) -> str:
    """Wrap a block in a fence long enough that its own backticks cannot end it.

    The proposed fix is model-written and may quote fenced code itself; three
    backticks would then close the block early and spill the rest of the review
    out as prose.
    """
    longest = max((len(run) for run in re.findall(r"`+", body)), default=0)
    ticks = "`" * max(3, longest + 1)
    return f"{ticks}{lang}\n{body}\n{ticks}"


def propose_code(f: dict) -> str:
    """The fix as code: the panel's sketch, fenced in the file's language.

    An issue is shown as code, so the change to it is shown as code too — a
    finding that quotes six lines of C and answers in a sentence leaves the
    contributor to guess the shape of the fix. This block is the panel's
    proposal, not something read from the checkout, hence the label: it is
    written against the lines quoted above and has been compiled by nobody.
    """
    snippet = str(f.get("fix_code") or "").strip("\n").rstrip()
    if not snippet:
        return "_The panel proposed no sample or pseudo-code for this fix._"
    body = snippet.splitlines()[:FIX_CODE_MAX_LINES]
    if len(snippet.splitlines()) > FIX_CODE_MAX_LINES:
        body.append(f"[... clipped at {FIX_CODE_MAX_LINES} lines ...]")
    lang = FENCE_LANGS.get(Path(str(f.get("file") or "")).suffix, "")
    return "\n".join([
        "Suggested change — a sketch to adapt, not a patch to apply:",
        "",
        _fence("\n".join(body), lang),
    ])


def render_issue(number: int, f: dict, clone: Path) -> str:
    """One blocking finding, as its own section: where, the code, why, the fix."""
    sev = f.get("severity", "major")
    lines = [f"## Issue {number} — {sev} in {_location(f)}", ""]
    lines += [quote_code(clone, f), ""]
    problem = _one_line(f.get("message"))
    lines += [f"**Problem.** {problem}" if problem
              else "**Problem.** _The panel recorded no description for this finding._", ""]
    fix = _one_line(f.get("fix"))
    lines += [f"**How to change it.** {fix}" if fix
              else "**How to change it.** _The panel proposed no fix for this finding._", ""]
    lines += [propose_code(f), ""]
    return "\n".join(lines)


def render_summary(verdict: str, findings: list[dict], clone: Path) -> str:
    """The deterministic head of the review: the decision, then one issue at a time.

    The panel writes prose; a contributor reading a GitHub notification needs
    the decision, and then — for each thing that blocks the merge — the code it
    is about and what to do to it. So the verdict is a line of its own, and
    every blocking finding gets its own section carrying its own quoted code,
    problem and fix. Two issues never share a section: a section that names two
    problems gets fixed halfway. Suggestions stay a plain list below, one per
    line, because a nit given the weight of a section reads like a blocker.
    """
    rank = {"blocker": 0, "major": 1, "nit": 2, "info": 3}
    findings = sorted((f for f in findings if isinstance(f, dict)),
                      key=lambda f: rank.get(f.get("severity", "info"), 4))
    blocking = [f for f in findings if f.get("severity") in BLOCKING]
    suggestions = [f for f in findings if f.get("severity") not in BLOCKING]

    decision = "APPROVE" if verdict == "approve" else "REJECT"
    lines = ["## Summary", "", f"**Verdict: {decision}**", ""]
    if len(blocking) == 1:
        lines += ["One issue must be resolved before this can merge; "
                  "it has its own section below.", ""]
    elif blocking:
        lines += [f"{len(blocking)} issues must be resolved before this can merge, "
                  f"one section each below.", ""]
    elif verdict != "approve":
        lines += ["No blocking finding was recorded; the review below explains "
                  "why this is not an approval.", ""]
    for number, f in enumerate(blocking, start=1):
        lines.append(render_issue(number, f, clone))
    if suggestions:
        lines += ["## Suggestions", "",
                  "Not blocking; apply or decline them.", ""]
        lines += [f"- **{f.get('severity', 'info')}** {_location(f)} — {_one_line(f.get('message'))}"
                  for f in suggestions]
        lines.append("")
    return "\n".join(lines)


def render_checklist(checklist: dict) -> str:
    """The record that all seven checks were walked."""
    if not isinstance(checklist, dict) or not checklist:
        return ""
    icons = {"pass": "✅", "concern": "⚠️", "blocker": "⛔"}
    lines = ["", "### Review checklist", "", "| Check | Status | Note |", "| --- | --- | --- |"]
    for key, title in CHECK_TITLES.items():
        entry = checklist.get(key)
        if isinstance(entry, dict):
            status = str(entry.get("status", "?")).lower()
            note = str(entry.get("note", "")).replace("|", "\\|").replace("\n", " ")
        else:
            status, note = "?", "(not reported by the panel)"
        lines.append(f"| {title} | {icons.get(status, '❔')} {status} | {note} |")
    return "\n".join(lines)


def run_session(session) -> dict:
    result = session.run()
    print(
        f"\npanel finished: {result.turns_completed} turns, "
        f"{result.rounds_run} rounds, last phase {result.phase_reached!r}, "
        f"ended {result.end_reason!r}",
        file=sys.stderr,
    )
    return result


def handle_pr(args: argparse.Namespace, provider, profile: Path) -> int:
    pr = github_io.fetch_pr(args.repo, args.number)
    diff = github_io.fetch_pr_diff(args.repo, args.number)

    clone = git_io.ensure_clone(args.workdir, args.repo)
    git_io.assert_clone_clean(clone)
    base = resolve_base_branch(args.repo, profile, args.base_branch, pr.get("baseRefName"))
    git_io.reset_to_branch(clone, base)
    short_sha = (pr.get("headRefOid") or "")[:8] or "nosha"
    branch = git_io.checkout_pr(clone, args.repo, args.number, short_sha)
    print(
        f"checked out PR #{args.number} (base: {base}) into {clone} on branch {branch}",
        file=sys.stderr,
    )

    facts = repo_facts.collect(clone, diff)
    session = session_builder.build_pr_session(
        topic=build_pr_topic(pr, diff, facts, clone, profile),
        clone=clone,
        provider=provider,
        model=args.llm_model,
        transcript=args.transcript,
        max_turns=args.max_turns,
    )
    result = run_session(session)
    require_completed_panel(result)

    fields, override = downgrade_if_needed(dict(result.fields))
    body = require_body(fields, result, "review_body")

    panel_verdict = fields.get("verdict", "comment")
    if panel_verdict not in ("approve", "comment"):
        panel_verdict = "comment"
    verdict = panel_verdict
    if verdict == "approve" and not args.allow_approve:
        verdict = "comment"
        gate_note = (
            "_Note: the panel proposed `approve`; posting as comment "
            "(run with `--allow-approve` to enable real approvals)._"
        )
        override = f"{override}\n\n{gate_note}" if override else gate_note

    # The summary states the panel's own decision, not how it is posted: with
    # `approve` gated by --allow-approve, the note above says why the two differ.
    head = render_summary(panel_verdict, fields.get("findings") or [], clone)
    if override:
        head = f"{head.rstrip()}\n\n{override}"
    body = f"{head.rstrip()}\n\n{body.strip()}"
    body = body.rstrip() + render_checklist(fields.get("checklist") or {})
    body += FOOTER_TEMPLATE.format(model=args.llm_model)

    if args.dry_run:
        print(f"[dry-run] would post `{verdict}` review on PR #{args.number}:\n")
        print(body)
        return 0

    github_io.post_pr_review(
        args.repo, args.number,
        approve=(verdict == "approve"),
        body=body,
    )
    print(f"posted `{verdict}` review on PR #{args.number}")
    return 0


def handle_issue(args: argparse.Namespace, provider, profile: Path) -> int:
    issue = github_io.fetch_issue(args.repo, args.number)

    clone = git_io.ensure_clone(args.workdir, args.repo)
    git_io.assert_clone_clean(clone)
    base = resolve_base_branch(args.repo, profile, args.base_branch, None)
    git_io.reset_to_branch(clone, base)
    print(f"checked out {args.repo} at {base} into {clone}", file=sys.stderr)

    session = session_builder.build_issue_session(
        topic=build_issue_topic(issue, clone, profile),
        clone=clone,
        provider=provider,
        model=args.llm_model,
        transcript=args.transcript,
        max_turns=args.max_turns,
    )
    result = run_session(session)
    require_completed_panel(result)

    fields = dict(result.fields)
    body = require_body(fields, result, "response_body")
    labels = [str(l) for l in (fields.get("labels") or [])]
    if labels:
        print(f"suggested labels (not applied): {', '.join(labels)}", file=sys.stderr)
    body += FOOTER_TEMPLATE.format(model=args.llm_model)

    if args.dry_run:
        print(f"[dry-run] would post comment on issue #{args.number}:\n")
        print(body)
        return 0

    github_io.post_issue_comment(args.repo, args.number, body)
    print(f"posted comment on issue #{args.number}")
    return 0


def main() -> int:
    args = parse_args()
    github_io.ensure_gh_ready()
    profile = resolve_profile(args.repo, args.prompts)
    # Which rubric the panel is judging against decides what the review means,
    # so a run on the generic fallback says so rather than looking curated.
    if args.prompts is not None:
        kind = "custom"
    else:
        kind = "generic" if profile == DEFAULT_PROFILE_DIR else "repo"
    print(f"reviewing {args.repo} with the {kind} profile at {profile}", file=sys.stderr)
    provider = session_builder.build_provider(args.api_key, args.api_base, args.timeout)
    if args.kind == "pr":
        return handle_pr(args, provider, profile)
    return handle_issue(args, provider, profile)


if __name__ == "__main__":
    sys.exit(main())
